# Setup
title:                systemhalted
tagline:             'Insane Thoughts'
description:         'I am just a DOS error'
url:                 http://systemhalted.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              systemhalted
  url:               http://systemhalted.in
  email:             insanethoughts@live.com

# Gems
plugins:
  - jekyll-paginate

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
