# Setup
title:                Renaissance
tagline:             'enlightenment-reawakening-reformation'
description:         'System Halted - I am just a DOS error'
url:                 https://systemhalted.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              systemhalted
  url:               https://systemhalted.in
  email:             insanethoughts@live.com


markdown: kramdown
# Gems
plugins:
  - jekyll-paginate

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Custom vars
version:             1.1.0
google_analytics_id: UA-36868278-1
