## Setup
title:            Palak Mathur
tagline:          'Tech Jaunt | A Journey of a Developer'
description:      'Web Presence of Palak Mathur.'
url:              palakmathur.in

gems:
  - jekyll-sitemap
